/* Auto-generated by contracts/ts/script.ts (user). Do not edit manually. */
export type Address = string;
export type Bytes = string;

export namespace EchoAccount {
	export type Call = {
		target: Address;
		value: bigint;
		data: Bytes;
	};
}

export namespace EchoFactory {
	export type EchoContext = {
		echoId: bigint;
		echoAccount: Address;
		echoGenesis: EchoGenesis.s_EchoGenesis;
	};
}

export namespace EchoGenesis {
	export type s_EchoGenesis = {
		_initialized: boolean;
		name: string;
		birthEpoch: bigint;
	};
	export type s_Params = {
		name: string;
	};
}

export namespace EchoLifeCycleModule {
	export type s_EchoLifeCycle = {
		hasBeenPetted: boolean;
		lastPettedCycle: bigint;
	};
}

export namespace EchoProgressModule {
	export type s_EchoProgress = {
		xp: bigint;
		level: bigint;
	};
}
