/* Auto-generated by contracts/ts/script.ts (user). Do not edit manually. */
export type Address = string;
export type Bytes = string;

export namespace Echo {
	export type s_Echo = {
		_initialized: boolean;
		name: string;
		birthEpoch: bigint;
	};
	export type s_Params = {
		name: string;
	};
}

export namespace EchoAccount {
	export type Call = {
		target: Address;
		value: bigint;
		data: Bytes;
	};
}

export namespace EchoFactory {
	export type EchoContext = {
		echoId: bigint;
		echoAccount: Address;
		echo: Echo.s_Echo;
	};
}

export namespace EchoLifeCycleModule {
	export type s_EchoLifeCycle = {
		lastPetAt: bigint;
	};
}

export namespace EchoLifeModule {
	export type EchoLife = {
		alive: boolean;
		lastPetAt: bigint;
	};
}

export namespace EchoLifecycle {
	export type EchoLifecycleState = {
		alive: boolean;
		lastPetAt: bigint;
	};
}

export namespace EchoProgressModule {
	export type EchoProgress = {
		xp: bigint;
		level: bigint;
	};
}
